In [1]:
from pathlib import Path
import numpy as np
import pandas as pd

In [2]:
csv_path="/mnt/data/spathak/CLaM-Annot-metadata.csv"

df=pd.read_csv(csv_path, delimiter=";")

pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)
#pd.set_option("display.max_rows", None)

In [3]:
to_drop=['MassShape','MassMargin',	'MassDensity',	'CalcificationMorphology',
         	'CalcificationDistribution',	'AsymmetryType',	'BIRADS', 'ConfidenceScore' ,
                'ImageHeight',	'ImageWidth' ,	'ViewID']

df=df.drop(to_drop, axis=1)



df = df.fillna("None")

df.head()

,PatientID,ExamID,ImageID,View,ROINum,BreastDensity,MammographicConspicuity,AbnormalityType,MammographyDiagnosis,PathologyDiagnosis,PatientGroundtruth,ImagePath,ROIPath
0,1,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529438.829540,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24939309.435922,L CC,R1,D,Moderately visible,Mass,Malignant,Malignant,Malignant,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529438.829540/L CC_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24939312.782252/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24939309.435922_processed.png,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529438.829540/L CC_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24939312.782252/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24939309.435922_binarymask_R1.png
1,1,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529438.829540,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24632543.764620,L MLO,None,D,None visible,None,None,None,Malignant,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529438.829540/L MLO_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24632545.679900/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24632543.764620_processed.png,None
2,1,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529438.829540,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529436.340289,R CC,None,D,None visible,None,None,None,Malignant,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529438.829540/R CC_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529439.467027/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529436.340289_processed.png,None
3,1,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529438.829540,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24636597.329390,R MLO,None,D,None visible,None,None,None,Malignant,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529438.829540/R MLO_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24636600.494593/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24636597.329390_processed.png,None
4,2,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.23398232.552346,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.23398229.955487,L CC,R1,B,Clearly visible,Calcification,Benign,None,Malignant,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.23398232.552346/L CC_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.23398233.463490/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.23398229.955487_processed.png,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.23398232.552346/L CC_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.23398233.463490/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.23398229.955487_binarymask_R1.png

In [4]:
df

,PatientID,ExamID,ImageID,View,ROINum,BreastDensity,MammographicConspicuity,AbnormalityType,MammographyDiagnosis,PathologyDiagnosis,PatientGroundtruth,ImagePath,ROIPath
0,1,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529438.829540,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24939309.435922,L CC,R1,D,Moderately visible,Mass,Malignant,Malignant,Malignant,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529438.829540/L CC_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24939312.782252/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24939309.435922_processed.png,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529438.829540/L CC_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24939312.782252/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24939309.435922_binarymask_R1.png
1,1,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529438.829540,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24632543.764620,L MLO,None,D,None visible,None,None,None,Malignant,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529438.829540/L MLO_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24632545.679900/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24632543.764620_processed.png,None
2,1,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529438.829540,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529436.340289,R CC,None,D,None visible,None,None,None,Malignant,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529438.829540/R CC_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529439.467027/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529436.340289_processed.png,None
3,1,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529438.829540,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24636597.329390,R MLO,None,D,None visible,None,None,None,Malignant,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24529438.829540/R MLO_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24636600.494593/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.24636597.329390_processed.png,None
4,2,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.23398232.552346,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.23398229.955487,L CC,R1,B,Clearly visible,Calcification,Benign,None,Malignant,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.23398232.552346/L CC_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.23398233.463490/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.23398229.955487_processed.png,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.23398232.552346/L CC_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.23398233.463490/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.23398229.955487_binarymask_R1.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...
489,99,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.20823936.661542,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.20823930.795989,R MLO,R2,B,Clearly visible,Calcification,Benign,None,Benign,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.20823936.661542/R MLO_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.20823938.931812/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.20823930.795989_processed.png,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.20823936.661542/R MLO_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.20823938.931812/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.20823930.795989_binarymask_R2.png
490,100,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25781440.377996,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.26314665.676295,L CC,R1,C,Clearly visible,Mass,Malignant,Malignant,Malignant,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25781440.377996/L CC_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.26314669.440972/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.26314665.676295_processed.png,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25781440.377996/L CC_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.26314669.440972/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.26314665.676295_binarymask_R1.png
491,100,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25781440.377996,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25806780.829157,L MLO,R1,C,Clearly visible,Mass,Malignant,Malignant,Malignant,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25781440.377996/L MLO_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25806782.662787/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25806780.829157_processed.png,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25781440.377996/L MLO_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25806782.662787/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25806780.829157_binarymask_R1.png
492,100,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25781440.377996,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25781438.961177,R CC,R1,C,Clearly visible,Calcification,Benign,None,Malignant,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25781440.377996/R CC_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25781441.872901/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25781438.961177_processed.png,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25781440.377996/R CC_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25781441.872901/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25781438.961177_binarymask_R1.png
493,100,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25781440.377996,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25986853.897145,R MLO,None,C,None visible,None,None,None,Malignant,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25781440.377996/R MLO_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25986856.726300/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.25986853.897145_processed.png,None

In [19]:
df["ImageID"].nunique()

416

### Patients with at least one "Mass" abnormality mammogram

Each patient has 4 mammogram samples L/R CC/MLO. If a mass is present it might be visible in some views but not in all.

In [6]:
df.loc[df["AbnormalityType"] == "Mass", "PatientID"].nunique()

67

In [27]:
mass_patient_ids = df.loc[
    df["AbnormalityType"] == "Mass",
    "PatientID"
].unique()

array([  1,   3,   4,   6,   7,   9,  10,  11,  16,  17,  18,  19,  20,
        21,  23,  26,  29,  30,  31,  33,  35,  36,  37,  39,  40,  42,
        43,  46,  47,  48,  49,  50,  51,  53,  54,  55,  56,  58,  59,
        60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
        73,  76,  77,  78,  79,  80,  85,  88,  92,  93,  95,  96,  98,
        99, 100])

### How many patients have malignant tumors and how many benign?
25 benign \
42 malignant

In [21]:
malignant_patient_ids = (
    df.groupby("PatientID")
      .filter(lambda g: (
          (g["AbnormalityType"] == "Mass") &
          (g["PatientGroundtruth"] == "Malignant")
      ).any())
      ["PatientID"]
      .unique()
)


benign_patient_ids = (
    df.groupby("PatientID")
      .filter(lambda g: (
          (g["AbnormalityType"] == "Mass") &
          (g["PatientGroundtruth"] == "Benign")
      ).any())
      ["PatientID"]
      .unique()
)




len(benign_patient_ids)

25

In [4]:
# Patients with at least one Mass
mass_patients = df.loc[
    df["AbnormalityType"] == "Mass", "PatientID"
].unique()

# All images containing Mass from those patients
mass_images = df[
    (df["PatientID"].isin(mass_patients)) &
    (df["AbnormalityType"] == "Mass")
]

all_images_mass_patients=df[
    (df["PatientID"].isin(mass_patients)) 
]

print(len(all_images_mass_patients))

n_mass_images = len(mass_images)

print(n_mass_images)


malignant_patients = (
    df.loc[
        (df["AbnormalityType"] == "Mass") &
        (df["PatientGroundtruth"] == "Malignant"),
        "PatientID"
    ]
    .unique()
)

malignant_mass_images = df[
    (df["PatientID"].isin(malignant_patients)) &
    (df["AbnormalityType"] == "Mass")
]

print(len(malignant_mass_images))


benign_patients = (
    df.loc[
        (df["AbnormalityType"] == "Mass") &
        (df["PatientGroundtruth"] == "Benign"),
        "PatientID"
    ]
    .unique()
)

benign_mass_images = df[
    (df["PatientID"].isin(benign_patients)) &
    (df["AbnormalityType"] == "Mass")
]

print(len(benign_mass_images))

336
159
106
53

In [6]:
malignant_mass_images.to_pickle("./dataset_splits/ZGT_malignant_mass_images.pkl")
benign_mass_images.to_pickle("./dataset_splits/ZGT_benign_mass_images.pkl")

In [22]:
shared_patients = set(malignant_mass_images["PatientID"]) & set(benign_mass_images["PatientID"])

len(shared_patients)

0

In [7]:

no_mass_patients = (
    df.groupby("PatientID")
      .filter(lambda g: (g["AbnormalityType"] != "Mass").all())
)

print(len(no_mass_patients))

n_images = no_mass_patients["ImageID"].nunique()

print(n_images)

158
140

In [9]:
# Patients with at least one Mass image
mass_patients = df.loc[
    df["AbnormalityType"] == "Mass",
    "PatientID"
].unique()

print(len(mass_patients))

# Non-Mass images belonging to those patients
non_mass_images_of_mass_patients = df[
    (df["PatientID"].isin(mass_patients)) &
    (df["AbnormalityType"] != "Mass")
]

print(len(non_mass_images_of_mass_patients))

# Count images
n_images = non_mass_images_of_mass_patients["ImagePath"].nunique()

print(n_images)

67
177
158

In [59]:
df.filter(malignant_patient_ids)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[494 rows x 0 columns]

### Breast density distribution

In [26]:
mass_patients = df.loc[
    df["AbnormalityType"] == "Mass",
    "PatientID"
].unique()

mass_patients_df=df[df["PatientID"].isin(mass_patients)]

patient_density = (
    df.loc[df["PatientID"].isin(mass_patients)]
      .groupby("PatientID")["BreastDensity"]
      .first()
)


density_counts = patient_density.value_counts()

density_counts

BreastDensity
B    35
C    20
D     8
A     4
Name: count, dtype: int64

In [8]:
df.columns

Index(['PatientID', 'ExamID', 'ImageID', 'View', 'ROINum', 'BreastDensity',
       'MammographicConspicuity', 'AbnormalityType', 'MammographyDiagnosis',
       'PathologyDiagnosis', 'PatientGroundtruth', 'ImagePath', 'ROIPath'],
      dtype='str')

In [29]:
df_breast_bc_patients = (
    df.loc[
        (df["AbnormalityType"] == "Mass") &
        (df['BreastDensity'].isin(["B","C"])),
        "PatientID"
    ]
    .unique()
)

df_breast_bc_images = df[
    (df["PatientID"].isin(df_breast_bc_patients)) &
    (df["AbnormalityType"] == "Mass")
]



df_breast_ad_patients = (
    df.loc[
        (df["AbnormalityType"] == "Mass") &
        (df['BreastDensity'].isin(["A","D"])),
        "PatientID"
    ]
    .unique()
)

df_breast_ad_images = df[
    (df["PatientID"].isin(df_breast_ad_patients)) &
    (df["AbnormalityType"] == "Mass")
]

print(len(df_breast_bc_images))
print(len(df_breast_ad_images))

132
38

In [30]:
shared_patients = set(df_breast_bc_images["PatientID"]) & set(df_breast_ad_images["PatientID"])

shared_patients

{39, 40, 80, 98}

In [ ]:
mass_patients = df.loc[
    df["AbnormalityType"] == "Mass",
    "PatientID"
].unique()

mass_patients_df=df[df["PatientID"].isin(mass_patients)]

In [32]:
csv_path="/mnt/data/spathak/CLaM-Annot-metadata.csv"

df=pd.read_csv(csv_path, delimiter=";")

density_counts_per_patient = (
    df.groupby("PatientID")["BreastDensity"]
      .nunique()
)

patients_multiple_density = density_counts_per_patient[
    density_counts_per_patient > 1
]

n_patients_multiple_density = len(patients_multiple_density)

print(n_patients_multiple_density)

22

In [31]:
mass_df = df[df["AbnormalityType"] == "Mass"]

density_counts_per_patient = (
    mass_df.groupby("PatientID")["BreastDensity"]
      .nunique()
)

patients_multiple_density = density_counts_per_patient[
    density_counts_per_patient > 1
]

len(patients_multiple_density)

6

In [36]:
patients_multiple_density.index

Index([ 2,  6, 12, 13, 21, 23, 32, 36, 39, 40, 54, 62, 69, 71, 73, 80, 82, 85,
       87, 88, 98, 99],
      dtype='int64', name='PatientID')

### Mass distribution per conspicuity

In [51]:

df.loc[df["AbnormalityType"] == "Mass", "MammographicConspicuity"].value_counts()

MammographicConspicuity
Clearly visible       118
Moderately visible     41
Name: count, dtype: int64

In [57]:
df.loc[df["AbnormalityType"] == "Mass"] \
  .groupby(["PatientGroundtruth", "MammographicConspicuity"]) \
  .size()

PatientGroundtruth  MammographicConspicuity
Benign              Clearly visible            39
                    Moderately visible         14
Malignant           Clearly visible            79
                    Moderately visible         27
dtype: int64

### How many patients are there with just mass abnormality and how many with mass and calcification? 
### Do those with multiple abnormalities have masks which contain all objects in one mask?

In [38]:
mass_patient_abnormalities=df.loc[df['PatientID'].isin(mass_patients)].groupby('PatientID')['AbnormalityType'].unique()

mass_patient_abnormalities

PatientID
1                          [Mass, None]
3                 [Mass, Calcification]
4                 [Calcification, Mass]
6                          [Mass, None]
7                          [None, Mass]
                     ...
95                [Calcification, Mass]
96     [Asymmetry, Mass, Calcification]
98                         [None, Mass]
99                [Calcification, Mass]
100         [Mass, Calcification, None]
Name: AbnormalityType, Length: 67, dtype: object

In [43]:
df[df['PatientID']==3]

,PatientID,ImageID,View,ROINum,BreastDensity,MammographicConspicuity,AbnormalityType,MammographyDiagnosis,PathologyDiagnosis,PatientGroundtruth,ImagePath,ROIPath
8,3,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769087.9167098,L CC,R1,B,Clearly visible,Mass,Malignant,Malignant,Malignant,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769089.3298629/L CC_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769090.2143573/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769087.9167098_processed.png,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769089.3298629/L CC_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769090.2143573/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769087.9167098_binarymask_R1.png
9,3,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769087.9167098,L CC,R2,B,Clearly visible,Calcification,Malignant,Malignant,Malignant,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769089.3298629/L CC_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769090.2143573/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769087.9167098_processed.png,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769089.3298629/L CC_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769090.2143573/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769087.9167098_binarymask_R2.png
10,3,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3940197.1505577,L MLO,R1,B,Clearly visible,Mass,Malignant,Malignant,Malignant,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769089.3298629/L MLO_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3940199.5591924/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3940197.1505577_processed.png,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769089.3298629/L MLO_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3940199.5591924/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3940197.1505577_binarymask_R1.png
11,3,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3940197.1505577,L MLO,R2,B,Clearly visible,Calcification,Malignant,Malignant,Malignant,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769089.3298629/L MLO_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3940199.5591924/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3940197.1505577_processed.png,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769089.3298629/L MLO_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3940199.5591924/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3940197.1505577_binarymask_R2.png
12,3,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3886942.7749917,R CC,R1,B,Clearly visible,Calcification,Benign,None,Malignant,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769089.3298629/R CC_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3886945.6798060/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3886942.7749917_processed.png,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769089.3298629/R CC_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3886945.6798060/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3886942.7749917_binarymask_R1.png
13,3,1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3932974.9681964,R MLO,R1,B,Clearly visible,Calcification,Benign,None,Malignant,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769089.3298629/R MLO_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3932976.2366692/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3932974.9681964_processed.png,CLaM-Annot/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3769089.3298629/R MLO_1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3932976.2366692/1.2.826.0.1.3680043.2.526.11.40.1608721769240233.3932974.9681964_binarymask_R1.png